=== SahsaB/pk/System/Schemas/DocumentSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:complexType name="TFont">
    <xs:annotation>
      <xs:documentation xml:lang="ru">Параметры шрифта.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="Name" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="ru">Имя.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Size" type="xs:unsignedShort" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="ru">Размер.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Style" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="ru">Стиль.</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Bold"/>
            <xs:enumeration value="Italic"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Color" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="ru">Цвет.</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Red"/>
            <xs:enumeration value="Violet"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:all>
    <xs:attribute name="ID" type="xs:string">
      <xs:annotation>
        <xs:documentation xml:lang="ru">ID для ссылок.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:element name="Template">
    <xs:annotation>
      <xs:documentation xml:lang="ru">Корневой элемент.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:all>
        <xs:element name="Fonts">
          <xs:annotation>
            <xs:documentation xml:lang="ru">Шрифты, используемые в документе.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Font" type="TFont" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Шрифт.</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Document">
          <xs:annotation>
            <xs:documentation xml:lang="ru">Шаблон документа.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:choice>
              <xs:element name="Excel">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Часть для таблиц Excel.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:all>
                    <xs:element name="Placeholder" type="xs:string" minOccurs="0">
                      <xs:annotation>
                        <xs:documentation xml:lang="ru">Заменяемое ключевое слово.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="Structure">
                      <xs:annotation>
                        <xs:documentation xml:lang="ru">Форматирование таблицы.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Column" maxOccurs="unbounded">
                            <xs:annotation>
                              <xs:documentation xml:lang="ru">Столбец.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Caption" type="xs:string">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Заголовок.</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element name="Width" type="xs:unsignedShort" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Ширина.</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element name="CaptionFontID" type="xs:string" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Ссылка на шрифт по ID.</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element name="DataFontID" type="xs:string" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Ссылка на шрифт по ID.</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element name="Placeholder" type="xs:string" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Заменяемое ключевое слово.</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
              <xs:element name="Word">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Часть для документов Word.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:all>
                    <xs:element name="Properties" minOccurs="0">
                      <xs:annotation>
                        <xs:documentation xml:lang="ru">Параметры документа.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:all>
                          <xs:element name="Album" minOccurs="0">
                            <xs:annotation>
                              <xs:documentation xml:lang="ru">Альбомная ориентация.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType/>
                          </xs:element>
                          <xs:element name="A5" minOccurs="0">
                            <xs:annotation>
                              <xs:documentation xml:lang="ru">Формат A5.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType/>
                          </xs:element>
                          <xs:element name="Borders" minOccurs="0">
                            <xs:annotation>
                              <xs:documentation xml:lang="ru">Рамка.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType/>
                          </xs:element>
                          <xs:element name="Margins" minOccurs="0">
                            <xs:annotation>
                              <xs:documentation xml:lang="ru">Отступы по краям.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:all>
                                <xs:element name="Left" type="xs:unsignedShort" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Левый.</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element name="Top" type="xs:unsignedShort" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Верхний.</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element name="Right" type="xs:unsignedShort" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Правый.</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element name="Bottom" type="xs:unsignedShort" minOccurs="0">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Нижний.</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                              </xs:all>
                            </xs:complexType>
                          </xs:element>
                        </xs:all>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Structure">
                      <xs:annotation>
                        <xs:documentation xml:lang="ru">Структура документа.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Element" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:choice>
                                <xs:element name="Paragraph">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ru">Параграф (строка).</xs:documentation>
                                  </xs:annotation>
                                  <xs:complexType>
                                    <xs:all>
                                      <xs:element name="Alighment" minOccurs="0">
                                        <xs:annotation>
                                          <xs:documentation xml:lang="ru">Выравнивание.</xs:documentation>
                                        </xs:annotation>
                                        <xs:simpleType>
                                          <xs:restriction base="xs:string">
                                            <xs:enumeration value="Center"/>
                                            <xs:enumeration value="Right"/>
                                            <xs:enumeration value="Both"/>
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                      <xs:element name="FontID" type="xs:string" minOccurs="0">
                                        <xs:annotation>
                                          <xs:documentation xml:lang="ru">Ссылка на шрифт по ID.</xs:documentation>
                                        </xs:annotation>
                                      </xs:element>
                                      <xs:element name="Parts" minOccurs="0">
                                        <xs:annotation>
                                          <xs:documentation xml:lang="ru">Составные части параграфа.</xs:documentation>
                                        </xs:annotation>
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="Part" maxOccurs="unbounded">
                                              <xs:annotation>
                                                <xs:documentation xml:lang="ru">Часть параграфа.</xs:documentation>
                                              </xs:annotation>
                                              <xs:complexType>
                                                <xs:all>
                                                  <xs:element name="FontID" type="xs:string" minOccurs="0">
                                                    <xs:annotation>
                                                      <xs:documentation xml:lang="ru">Ссылка на шрифт по ID.</xs:documentation>
                                                    </xs:annotation>
                                                  </xs:element>
                                                  <xs:element name="Text">
                                                    <xs:annotation>
                                                      <xs:documentation xml:lang="ru">Простой текст.</xs:documentation>
                                                    </xs:annotation>
                                                    <xs:complexType>
                                                      <xs:choice>
                                                        <xs:element name="String" type="xs:string">
                                                          <xs:annotation>
                                                            <xs:documentation xml:lang="ru">Текст.</xs:documentation>
                                                          </xs:annotation>
                                                        </xs:element>
                                                        <xs:element name="Placeholder" type="xs:string">
                                                          <xs:annotation>
                                                            <xs:documentation xml:lang="ru">Заменяемое ключевое слово.</xs:documentation>
                                                          </xs:annotation>
                                                        </xs:element>
                                                      </xs:choice>
                                                    </xs:complexType>
                                                  </xs:element>
                                                </xs:all>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:all>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Table">
                                  <xs:complexType>
                                    <xs:annotation>
                                      <xs:documentation xml:lang="ru">Таблица.</xs:documentation>
                                    </xs:annotation>
                                    <xs:all>
                                      <xs:element name ="Numeration" type="xs:boolean">
                                        <xs:annotation>
                                          <xs:documentation xml:lang="ru">Создавать столбец с номерами строк.</xs:documentation>
                                        </xs:annotation>
                                      </xs:element>
                                      <xs:element name="Placeholder" type="xs:string">
                                        <xs:annotation>
                                          <xs:documentation xml:lang="ru">Заменяемое ключевое слово.</xs:documentation>
                                        </xs:annotation>
                                      </xs:element>
                                      <xs:element name="Structure">
                                        <xs:annotation>
                                          <xs:documentation xml:lang="ru">Форматирование таблицы.</xs:documentation>
                                        </xs:annotation>
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="Column" maxOccurs="unbounded">
                                              <xs:annotation>
                                                <xs:documentation xml:lang="ru">Столбец.</xs:documentation>
                                              </xs:annotation>
                                              <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Caption" type="xs:string">
                                                    <xs:annotation>
                                                      <xs:documentation xml:lang="ru">Заголовок.</xs:documentation>
                                                    </xs:annotation>
                                                  </xs:element>
                                                  <xs:element name="Width" type="xs:unsignedShort" minOccurs="0">
                                                    <xs:annotation>
                                                      <xs:documentation xml:lang="ru">Ширина.</xs:documentation>
                                                    </xs:annotation>
                                                  </xs:element>
                                                  <xs:element name="CaptionFontID" type="xs:string" minOccurs="0">
                                                    <xs:annotation>
                                                      <xs:documentation xml:lang="ru">Ссылка на шрифт по ID.</xs:documentation>
                                                    </xs:annotation>
                                                  </xs:element>
                                                  <xs:element name="DataFontID" type="xs:string" minOccurs="0">
                                                    <xs:annotation>
                                                      <xs:documentation xml:lang="ru">Ссылка на шрифт по ID.</xs:documentation>
                                                    </xs:annotation>
                                                  </xs:element>
                                                </xs:sequence>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:all>
                                  </xs:complexType>
                                </xs:element>
                              </xs:choice>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SahsaB/pk/System/PK/PK/DocumentTemplates/PercRecordFaceM.xml
<?xml version="1.0" encoding="utf-8"?>
<Template
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="..\Schemas\DocumentSchema.xsd">
  <Fonts>
    <Font ID="Small">
      <Name>Arial</Name>
      <Size>12</Size>
    </Font>
    <Font ID="Usual">
      <Name>Arial</Name>
      <Size>12</Size>
    </Font>
    <Font ID="16">
      <Name>Arial</Name>
      <Size>16</Size>
    </Font>
    <Font ID="24">
      <Name>Arial</Name>
      <Size>24</Size>
    </Font>
    <Font ID="Large">
      <Name>Arial</Name>
      <Size>32</Size>
    </Font>
    <Font ID="LargeBold">
      <Name>Arial</Name>
      <Size>32</Size>
      <Style>Bold</Style>
    </Font>
  </Fonts>
  <Document>
    <Word>
      <Properties>
        <A5/>
        <Album/>
        <Margins>
          <Left>35</Left>
          <Top>35</Top>
        </Margins>
      </Properties>
      <Structure>
        <Element>
          <FixedTable>
            <ColumnsParameters>
              <Columns>
                <ColumnWidth>550</ColumnWidth>
                <ColumnWidth>9700</ColumnWidth>
              </Columns>
            </ColumnsParameters>
            <Borders>
              <Left>
                <Style>None</Style>
              </Left>
              <Top>
                <Style>None</Style>
              </Top>
              <Right>
                <Style>None</Style>
              </Right>
              <Bottom>
                <Style>None</Style>
              </Bottom>
            </Borders>
            <Rows>
              <Row>
                <Cells>
                  <Cell Column="0">
                    <Borders>
                      <Right>
                        <Style>Dashed</Style>
                      </Right>
                      <Bottom>
                        <Style>None</Style>
                      </Bottom>
                    </Borders>
                    <Paragraphs>
                      <Paragraph>
                        <FontID>16</FontID>
                        <Parts>
                          <Part>
                            <Text>
                              <String>Иванов</String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String>--</String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String>И.И.</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                    </Paragraphs>
                  </Cell>
                  <Cell Column="1">
                    <Borders>
                      <Left>
                        <Style>Dashed</Style>
                      </Left>
                      <Bottom>
                        <Style>None</Style>
                      </Bottom>
                    </Borders>
                    <Paragraphs>
                      <Paragraph>
                        <FontID>Large</FontID>
                        <Alighment>Right</Alighment>
                        <Parts>
                          <Part>
                            <Text>
                              <String>№</String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String>5</String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String> |</String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String>АБР</String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String>|</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                      <Paragraph/>
                      <Paragraph>
                        <FontID>Usual</FontID>
                        <Alighment>Right</Alighment>
                        <Parts>
                          <Part>
                            <Text>
                              <String>Направление подготовки </String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String>НАПРАВЛЕНИЕ</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                      <Paragraph>
                        <FontID>Usual</FontID>
                        <Alighment>Right</Alighment>
                        <Parts>
                          <Part>
                            <Text>
                              <String>Магистрская программа </String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String>ПРОГРАММА</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                      <Paragraph>
                        <FontID>Usual</FontID>
                        <Alighment>Right</Alighment>
                        <Parts>
                          <Part>
                            <Text>
                              <String>Форма обучения </String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String>ОчнаЯ</String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String> </String>
                            </Text>
                          </Part>
                          <Part>
                            <Text>
                              <String>БюджеТ</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                      <Paragraph/>
                      <Paragraph>
                        <FontID>LargeBold</FontID>
                        <Alighment>Center</Alighment>
                        <Parts>
                          <Part>
                            <FontID>LargeBold</FontID>
                            <Text>
                              <String>Иванов</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                      <Paragraph>
                        <FontID>Large</FontID>
                        <Alighment>Center</Alighment>
                        <Parts>
                          <Part>
                            <Text>
                              <String>Иван Иванович</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                      <Paragraph/>
                      <Paragraph/>
                    </Paragraphs>
                  </Cell>
                </Cells>
              </Row>
              <Row>
                <Cells>
                  <Cell Column="0">
                    <Borders>
                      <Right>
                        <Style>Dashed</Style>
                      </Right>
                      <Top>
                        <Style>None</Style>
                      </Top>
                    </Borders>
                    <Paragraphs>
                      <Paragraph>
                        <FontID>24</FontID>
                        <Parts>
                          <Part>
                            <Text>
                              <String>М</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                    </Paragraphs>
                  </Cell>
                  <Cell Column="1">
                    <Borders>
                      <Left>
                        <Style>Dashed</Style>
                      </Left>
                      <Top>
                        <Style>None</Style>
                      </Top>
                    </Borders>
                    <Paragraphs>
                      <Paragraph>
                        <FontID>Small</FontID>
                        <Alighment>Center</Alighment>
                        <Parts>
                          <Part>
                            <Text>
                              <String>магистратура</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                      <Paragraph>
                        <FontID>Large</FontID>
                        <Alighment>Center</Alighment>
                        <Parts>
                          <Part>
                            <Text>
                              <String>2017</String>
                            </Text>
                          </Part>
                        </Parts>
                      </Paragraph>
                    </Paragraphs>
                  </Cell>
                </Cells>
              </Row>
            </Rows>
          </FixedTable>
        </Element>
      </Structure>
    </Word>
  </Document>
</Template>
